## Programming Assignment #2

# Problem #1: Reproducible Normalization

In [12]:
#Important Convention rule
import numpy as np

np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))

# Normalizing array using the given formula
X_normalized = (X - X.mean()) / np.std(X)

# Display all required checks
print("The randomized array is:\n", X)
print("The normalized array is:\n", X_normalized)
print("The mean of the normalized array is:", X_normalized.mean())
print("The standard deviation of the normalized array is:", np.std(X_normalized))

# Save normalized array
np.save("X_normalized.npy", X_normalized)

The randomized array is:
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]
The normalized array is:
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]
The mean of the normalized array is: 0.0
The standard deviation of the normalized array is: 0.9999999999999999


## Problem #2: Cubes Divisible by 4 problem

In [13]:
import numpy as np

# Creating the first 100 positive integers and using a boolean condition
C = np.arange(1, 101).reshape(10, 10) ** 3
div_by_4 = C[C % 4 == 0]

# Display all required checks
print("The shape of the original array is:", C.shape)
print("The array of the elements divisible by 4 is:\n", div_by_4)
print("The number of elements that are divisible by 4 is:", div_by_4.size)

# Saving array
np.save("div_by_4.npy", div_by_4)

The shape of the original array is: (10, 10)
The array of the elements divisible by 4 is:
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]
The number of elements that are divisible by 4 is: 50


## Problem #3 : Above-mean squares

In [15]:
import numpy as np
# PROBLEM C: Above-Mean Squares

# creating 6x6 array (S)
S = (np.arange(1, 37) ** 2).reshape(6, 6)
# compute mean of all elements of S and store to S_mean
S_mean = S.mean()  
# stored values into above_mean
above_mean = S[S > S_mean]

# Display required checks
print("The original array is:\n", S)
print("The mean of the array is:", S_mean)
print("The elements that are greater than the mean are:\n", above_mean)
print("The number of selected elements is:", above_mean.size)  # <-- Missing check

# Saving  array
np.save("above_mean.npy", above_mean)

The original array is:
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]
The mean of the array is: 450.1666666666667
The elements that are greater than the mean are:
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]
The number of selected elements is: 15
